/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsSecretNoteRouteImport } from './routes/tools.secret-note'
import { Route as ToolsQrTrailRouteImport } from './routes/tools.qr-trail'
import { Route as ToolsQrSecretRouteImport } from './routes/tools.qr-secret'
import { Route as ToolsNthLetterRouteImport } from './routes/tools.nth-letter'
import { Route as ToolsMetadataRouteImport } from './routes/tools.metadata'
import { Route as ToolsKonamiRouteImport } from './routes/tools.konami'
import { Route as ToolsInvisibleTextRouteImport } from './routes/tools.invisible-text'
import { Route as ToolsImageWatermarkRouteImport } from './routes/tools.image-watermark'
import { Route as ToolsImageSecretRouteImport } from './routes/tools.image-secret'
import { Route as ToolsHtmlCommentRouteImport } from './routes/tools.html-comment'
import { Route as ToolsHmacRouteImport } from './routes/tools.hmac'
import { Route as ToolsHashRouteImport } from './routes/tools.hash'
import { Route as ToolsFinalDoorRouteImport } from './routes/tools.final-door'
import { Route as ToolsFileChecksumRouteImport } from './routes/tools.file-checksum'
import { Route as ToolsEncryptRouteImport } from './routes/tools.encrypt'
import { Route as ToolsEncoderRouteImport } from './routes/tools.encoder'
import { Route as ToolsCssHiddenTextRouteImport } from './routes/tools.css-hidden-text'
import { Route as ToolsConsoleMessageRouteImport } from './routes/tools.console-message'
import { Route as ToolsChallengeRouteImport } from './routes/tools.challenge'
import { Route as ToolsAcrosticRouteImport } from './routes/tools.acrostic'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSecretNoteRoute = ToolsSecretNoteRouteImport.update({
  id: '/secret-note',
  path: '/secret-note',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsQrTrailRoute = ToolsQrTrailRouteImport.update({
  id: '/qr-trail',
  path: '/qr-trail',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsQrSecretRoute = ToolsQrSecretRouteImport.update({
  id: '/qr-secret',
  path: '/qr-secret',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsNthLetterRoute = ToolsNthLetterRouteImport.update({
  id: '/nth-letter',
  path: '/nth-letter',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMetadataRoute = ToolsMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsKonamiRoute = ToolsKonamiRouteImport.update({
  id: '/konami',
  path: '/konami',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsInvisibleTextRoute = ToolsInvisibleTextRouteImport.update({
  id: '/invisible-text',
  path: '/invisible-text',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsImageWatermarkRoute = ToolsImageWatermarkRouteImport.update({
  id: '/image-watermark',
  path: '/image-watermark',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsImageSecretRoute = ToolsImageSecretRouteImport.update({
  id: '/image-secret',
  path: '/image-secret',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHtmlCommentRoute = ToolsHtmlCommentRouteImport.update({
  id: '/html-comment',
  path: '/html-comment',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHmacRoute = ToolsHmacRouteImport.update({
  id: '/hmac',
  path: '/hmac',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHashRoute = ToolsHashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFinalDoorRoute = ToolsFinalDoorRouteImport.update({
  id: '/final-door',
  path: '/final-door',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFileChecksumRoute = ToolsFileChecksumRouteImport.update({
  id: '/file-checksum',
  path: '/file-checksum',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsEncryptRoute = ToolsEncryptRouteImport.update({
  id: '/encrypt',
  path: '/encrypt',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsEncoderRoute = ToolsEncoderRouteImport.update({
  id: '/encoder',
  path: '/encoder',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCssHiddenTextRoute = ToolsCssHiddenTextRouteImport.update({
  id: '/css-hidden-text',
  path: '/css-hidden-text',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsConsoleMessageRoute = ToolsConsoleMessageRouteImport.update({
  id: '/console-message',
  path: '/console-message',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsChallengeRoute = ToolsChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsAcrosticRoute = ToolsAcrosticRouteImport.update({
  id: '/acrostic',
  path: '/acrostic',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/puzzles': typeof PuzzlesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/acrostic': typeof ToolsAcrosticRoute
  '/tools/challenge': typeof ToolsChallengeRoute
  '/tools/console-message': typeof ToolsConsoleMessageRoute
  '/tools/css-hidden-text': typeof ToolsCssHiddenTextRoute
  '/tools/encoder': typeof ToolsEncoderRoute
  '/tools/encrypt': typeof ToolsEncryptRoute
  '/tools/file-checksum': typeof ToolsFileChecksumRoute
  '/tools/final-door': typeof ToolsFinalDoorRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/hmac': typeof ToolsHmacRoute
  '/tools/html-comment': typeof ToolsHtmlCommentRoute
  '/tools/image-secret': typeof ToolsImageSecretRoute
  '/tools/image-watermark': typeof ToolsImageWatermarkRoute
  '/tools/invisible-text': typeof ToolsInvisibleTextRoute
  '/tools/konami': typeof ToolsKonamiRoute
  '/tools/metadata': typeof ToolsMetadataRoute
  '/tools/nth-letter': typeof ToolsNthLetterRoute
  '/tools/qr-secret': typeof ToolsQrSecretRoute
  '/tools/qr-trail': typeof ToolsQrTrailRoute
  '/tools/secret-note': typeof ToolsSecretNoteRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/puzzles': typeof PuzzlesRoute
  '/tools/acrostic': typeof ToolsAcrosticRoute
  '/tools/challenge': typeof ToolsChallengeRoute
  '/tools/console-message': typeof ToolsConsoleMessageRoute
  '/tools/css-hidden-text': typeof ToolsCssHiddenTextRoute
  '/tools/encoder': typeof ToolsEncoderRoute
  '/tools/encrypt': typeof ToolsEncryptRoute
  '/tools/file-checksum': typeof ToolsFileChecksumRoute
  '/tools/final-door': typeof ToolsFinalDoorRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/hmac': typeof ToolsHmacRoute
  '/tools/html-comment': typeof ToolsHtmlCommentRoute
  '/tools/image-secret': typeof ToolsImageSecretRoute
  '/tools/image-watermark': typeof ToolsImageWatermarkRoute
  '/tools/invisible-text': typeof ToolsInvisibleTextRoute
  '/tools/konami': typeof ToolsKonamiRoute
  '/tools/metadata': typeof ToolsMetadataRoute
  '/tools/nth-letter': typeof ToolsNthLetterRoute
  '/tools/qr-secret': typeof ToolsQrSecretRoute
  '/tools/qr-trail': typeof ToolsQrTrailRoute
  '/tools/secret-note': typeof ToolsSecretNoteRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/puzzles': typeof PuzzlesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/acrostic': typeof ToolsAcrosticRoute
  '/tools/challenge': typeof ToolsChallengeRoute
  '/tools/console-message': typeof ToolsConsoleMessageRoute
  '/tools/css-hidden-text': typeof ToolsCssHiddenTextRoute
  '/tools/encoder': typeof ToolsEncoderRoute
  '/tools/encrypt': typeof ToolsEncryptRoute
  '/tools/file-checksum': typeof ToolsFileChecksumRoute
  '/tools/final-door': typeof ToolsFinalDoorRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/hmac': typeof ToolsHmacRoute
  '/tools/html-comment': typeof ToolsHtmlCommentRoute
  '/tools/image-secret': typeof ToolsImageSecretRoute
  '/tools/image-watermark': typeof ToolsImageWatermarkRoute
  '/tools/invisible-text': typeof ToolsInvisibleTextRoute
  '/tools/konami': typeof ToolsKonamiRoute
  '/tools/metadata': typeof ToolsMetadataRoute
  '/tools/nth-letter': typeof ToolsNthLetterRoute
  '/tools/qr-secret': typeof ToolsQrSecretRoute
  '/tools/qr-trail': typeof ToolsQrTrailRoute
  '/tools/secret-note': typeof ToolsSecretNoteRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/puzzles'
    | '/tools'
    | '/tools/acrostic'
    | '/tools/challenge'
    | '/tools/console-message'
    | '/tools/css-hidden-text'
    | '/tools/encoder'
    | '/tools/encrypt'
    | '/tools/file-checksum'
    | '/tools/final-door'
    | '/tools/hash'
    | '/tools/hmac'
    | '/tools/html-comment'
    | '/tools/image-secret'
    | '/tools/image-watermark'
    | '/tools/invisible-text'
    | '/tools/konami'
    | '/tools/metadata'
    | '/tools/nth-letter'
    | '/tools/qr-secret'
    | '/tools/qr-trail'
    | '/tools/secret-note'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/puzzles'
    | '/tools/acrostic'
    | '/tools/challenge'
    | '/tools/console-message'
    | '/tools/css-hidden-text'
    | '/tools/encoder'
    | '/tools/encrypt'
    | '/tools/file-checksum'
    | '/tools/final-door'
    | '/tools/hash'
    | '/tools/hmac'
    | '/tools/html-comment'
    | '/tools/image-secret'
    | '/tools/image-watermark'
    | '/tools/invisible-text'
    | '/tools/konami'
    | '/tools/metadata'
    | '/tools/nth-letter'
    | '/tools/qr-secret'
    | '/tools/qr-trail'
    | '/tools/secret-note'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/puzzles'
    | '/tools'
    | '/tools/acrostic'
    | '/tools/challenge'
    | '/tools/console-message'
    | '/tools/css-hidden-text'
    | '/tools/encoder'
    | '/tools/encrypt'
    | '/tools/file-checksum'
    | '/tools/final-door'
    | '/tools/hash'
    | '/tools/hmac'
    | '/tools/html-comment'
    | '/tools/image-secret'
    | '/tools/image-watermark'
    | '/tools/invisible-text'
    | '/tools/konami'
    | '/tools/metadata'
    | '/tools/nth-letter'
    | '/tools/qr-secret'
    | '/tools/qr-trail'
    | '/tools/secret-note'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  PuzzlesRoute: typeof PuzzlesRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/secret-note': {
      id: '/tools/secret-note'
      path: '/secret-note'
      fullPath: '/tools/secret-note'
      preLoaderRoute: typeof ToolsSecretNoteRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/qr-trail': {
      id: '/tools/qr-trail'
      path: '/qr-trail'
      fullPath: '/tools/qr-trail'
      preLoaderRoute: typeof ToolsQrTrailRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/qr-secret': {
      id: '/tools/qr-secret'
      path: '/qr-secret'
      fullPath: '/tools/qr-secret'
      preLoaderRoute: typeof ToolsQrSecretRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/nth-letter': {
      id: '/tools/nth-letter'
      path: '/nth-letter'
      fullPath: '/tools/nth-letter'
      preLoaderRoute: typeof ToolsNthLetterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/metadata': {
      id: '/tools/metadata'
      path: '/metadata'
      fullPath: '/tools/metadata'
      preLoaderRoute: typeof ToolsMetadataRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/konami': {
      id: '/tools/konami'
      path: '/konami'
      fullPath: '/tools/konami'
      preLoaderRoute: typeof ToolsKonamiRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/invisible-text': {
      id: '/tools/invisible-text'
      path: '/invisible-text'
      fullPath: '/tools/invisible-text'
      preLoaderRoute: typeof ToolsInvisibleTextRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/image-watermark': {
      id: '/tools/image-watermark'
      path: '/image-watermark'
      fullPath: '/tools/image-watermark'
      preLoaderRoute: typeof ToolsImageWatermarkRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/image-secret': {
      id: '/tools/image-secret'
      path: '/image-secret'
      fullPath: '/tools/image-secret'
      preLoaderRoute: typeof ToolsImageSecretRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/html-comment': {
      id: '/tools/html-comment'
      path: '/html-comment'
      fullPath: '/tools/html-comment'
      preLoaderRoute: typeof ToolsHtmlCommentRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/hmac': {
      id: '/tools/hmac'
      path: '/hmac'
      fullPath: '/tools/hmac'
      preLoaderRoute: typeof ToolsHmacRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/hash': {
      id: '/tools/hash'
      path: '/hash'
      fullPath: '/tools/hash'
      preLoaderRoute: typeof ToolsHashRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/final-door': {
      id: '/tools/final-door'
      path: '/final-door'
      fullPath: '/tools/final-door'
      preLoaderRoute: typeof ToolsFinalDoorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/file-checksum': {
      id: '/tools/file-checksum'
      path: '/file-checksum'
      fullPath: '/tools/file-checksum'
      preLoaderRoute: typeof ToolsFileChecksumRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/encrypt': {
      id: '/tools/encrypt'
      path: '/encrypt'
      fullPath: '/tools/encrypt'
      preLoaderRoute: typeof ToolsEncryptRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/encoder': {
      id: '/tools/encoder'
      path: '/encoder'
      fullPath: '/tools/encoder'
      preLoaderRoute: typeof ToolsEncoderRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/css-hidden-text': {
      id: '/tools/css-hidden-text'
      path: '/css-hidden-text'
      fullPath: '/tools/css-hidden-text'
      preLoaderRoute: typeof ToolsCssHiddenTextRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/console-message': {
      id: '/tools/console-message'
      path: '/console-message'
      fullPath: '/tools/console-message'
      preLoaderRoute: typeof ToolsConsoleMessageRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/challenge': {
      id: '/tools/challenge'
      path: '/challenge'
      fullPath: '/tools/challenge'
      preLoaderRoute: typeof ToolsChallengeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/acrostic': {
      id: '/tools/acrostic'
      path: '/acrostic'
      fullPath: '/tools/acrostic'
      preLoaderRoute: typeof ToolsAcrosticRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface ToolsRouteChildren {
  ToolsAcrosticRoute: typeof ToolsAcrosticRoute
  ToolsChallengeRoute: typeof ToolsChallengeRoute
  ToolsConsoleMessageRoute: typeof ToolsConsoleMessageRoute
  ToolsCssHiddenTextRoute: typeof ToolsCssHiddenTextRoute
  ToolsEncoderRoute: typeof ToolsEncoderRoute
  ToolsEncryptRoute: typeof ToolsEncryptRoute
  ToolsFileChecksumRoute: typeof ToolsFileChecksumRoute
  ToolsFinalDoorRoute: typeof ToolsFinalDoorRoute
  ToolsHashRoute: typeof ToolsHashRoute
  ToolsHmacRoute: typeof ToolsHmacRoute
  ToolsHtmlCommentRoute: typeof ToolsHtmlCommentRoute
  ToolsImageSecretRoute: typeof ToolsImageSecretRoute
  ToolsImageWatermarkRoute: typeof ToolsImageWatermarkRoute
  ToolsInvisibleTextRoute: typeof ToolsInvisibleTextRoute
  ToolsKonamiRoute: typeof ToolsKonamiRoute
  ToolsMetadataRoute: typeof ToolsMetadataRoute
  ToolsNthLetterRoute: typeof ToolsNthLetterRoute
  ToolsQrSecretRoute: typeof ToolsQrSecretRoute
  ToolsQrTrailRoute: typeof ToolsQrTrailRoute
  ToolsSecretNoteRoute: typeof ToolsSecretNoteRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsAcrosticRoute: ToolsAcrosticRoute,
  ToolsChallengeRoute: ToolsChallengeRoute,
  ToolsConsoleMessageRoute: ToolsConsoleMessageRoute,
  ToolsCssHiddenTextRoute: ToolsCssHiddenTextRoute,
  ToolsEncoderRoute: ToolsEncoderRoute,
  ToolsEncryptRoute: ToolsEncryptRoute,
  ToolsFileChecksumRoute: ToolsFileChecksumRoute,
  ToolsFinalDoorRoute: ToolsFinalDoorRoute,
  ToolsHashRoute: ToolsHashRoute,
  ToolsHmacRoute: ToolsHmacRoute,
  ToolsHtmlCommentRoute: ToolsHtmlCommentRoute,
  ToolsImageSecretRoute: ToolsImageSecretRoute,
  ToolsImageWatermarkRoute: ToolsImageWatermarkRoute,
  ToolsInvisibleTextRoute: ToolsInvisibleTextRoute,
  ToolsKonamiRoute: ToolsKonamiRoute,
  ToolsMetadataRoute: ToolsMetadataRoute,
  ToolsNthLetterRoute: ToolsNthLetterRoute,
  ToolsQrSecretRoute: ToolsQrSecretRoute,
  ToolsQrTrailRoute: ToolsQrTrailRoute,
  ToolsSecretNoteRoute: ToolsSecretNoteRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  PuzzlesRoute: PuzzlesRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
